fallback = 'ï‹'

[matching]
# Default Config: https://github.com/Lyr-7D1h/swayest_workstyle#default-config
'/War Thunder \(Vulkan, 64bit\)/' = 'ğŸ›©'
'/(C|c)aprine/' = 'ïŸ'                   # Messenger for Linux
'/(M|m)essenger/' = 'ïŸ'                 # Messenger for Linux
'/(M|m)essage/' = 'ïŸ'                   # Messenger for Linux
'/trash/' = 'ï‡¸'
'/Dolphin/' = 'î—¿'
'/imv/' = 'î˜'
'/git/' = 'ï‡“'
'discord' = 'ï’'
'balena-etcher' = 'ï‹›'
'/Steam/' = 'ï†¶'
'/Friends List/' = 'ï†¶'
'/(T|t)hunderbird/' = 'ïƒ '
'Insomnia' = 'ïˆ¶'
'Google-chrome' = 'ï‰¨'
'Chromium' = 'ï‰¨'
'Slack' = 'ï†˜'
'Code' = 'îœŒ'
'code-oss' = 'îœŒ'
'Spotify' = 'ï†¼'
'/(?i)Github/' = 'ï„“'
'firefox' = 'ï‰©'
'Nightly' = 'ï‰©'
'firefoxdeveloperedition' = 'ï‰©'
'/nvim ?\w*/' = 'î˜«'
'/npm/' = 'îœ'
'/node/' = 'îœ˜'
'/yarn/' = 'îœ˜'
'Alacritty' = 'ï„ '
